config/routes.rb
VLPBill::Application.routes.draw do
  resources :movies

  resources :bills

  resources :theaters
  resources :prints
  resources :cubes
  resources :ufos

end

app/models/Cube.rb
class Cube < Theater
  attr_accessible :email, :location, :name, :type
end

app/models/Print.rb
class Print < Theater
  attr_accessible :email, :location, :name, :type
end

app/models/UFO.rb
class UFO < Theater
  attr_accessible :email, :location, :name, :type
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  attr_accessible :amount, :date, :theater_id
  belongs_to :theaters
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :name
  has_many :theaters
end

app/models/theater.rb
class Theater < ActiveRecord::Base
  attr_accessible :email, :location, :name, :type
  has_many :bills
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bills }
    end
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    @bill = Bill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/new
  # GET /bills/new.json
  def new
    @bill = Bill.new
    @theater = Theater.find(params[:theater_id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/1/edit
  def edit
    @bill = Bill.find(params[:id])
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(params[:bill])

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render json: @bill, status: :created, location: @bill }
      else
        format.html { render action: "new" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bills/1
  # PUT /bills/1.json
  def update
    @bill = Bill.find(params[:id])

    respond_to do |format|
      if @bill.update_attributes(params[:bill])
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill = Bill.find(params[:id])
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to bills_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
  # GET /theaters
  # GET /theaters.json
  def index
    @theaters = Theater.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @theaters }
    end
  end

  # GET /theaters/1
  # GET /theaters/1.json
  def show
    @theater = Theater.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @theater }
    end
  end

  # GET /theaters/new
  # GET /theaters/new.json
  def new
    @theater = Theater.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @theater }
    end
  end

  # GET /theaters/1/edit
  def edit
    @theater = Theater.find(params[:id])
  end

  # POST /theaters
  # POST /theaters.json
  def create
    @theater = Theater.new(params[:theater])

    respond_to do |format|
      if @theater.save
        format.html { redirect_to @theater, notice: 'Theater was successfully created.' }
        format.json { render json: @theater, status: :created, location: @theater }
      else
        format.html { render action: "new" }
        format.json { render json: @theater.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /theaters/1
  # PUT /theaters/1.json
  def update
    @theater = Theater.find(params[:id])

    respond_to do |format|
      if @theater.update_attributes(params[:theater])
        format.html { redirect_to @theater, notice: 'Theater was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @theater.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theaters/1
  # DELETE /theaters/1.json
  def destroy
    @theater = Theater.find(params[:id])
    @theater.destroy

    respond_to do |format|
      format.html { redirect_to theaters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/theaters_helper.rb
module TheatersHelper
  def give_details bills
    bills.map{ |bill| "#{bill.date}:#{bill.amount}<br/>" }.flatten
  end
end

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.hidden_field :theater_id, :value => @theater.id %>
    <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<h1>Listing bills</h1>

<table>
  <tr>
    <th>Amount</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bills.each do |bill| %>
  <tr>
    <td><%= bill.amount %></td>
    <td><%= bill.date %></td>
    <td><%= link_to 'Show', bill %></td>
    <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
    <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bill', new_bill_path %>

app/views/bills/new.html.erb
<h1>New bill</h1>

<p>Theater name :<%= @theater.name %></p>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Amount:</b>
  <%= @bill.amount %>
</p>

<p>
  <b>Date:</b>
  <%= @bill.date %>
</p>


<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VLPBill</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movies.each do |movie| %>
  <tr>
    <td><%= movie.name %></td>
    <td><%= link_to 'Show', movie %></td>
    <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
    <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @movie.name %>
</p>

<%= @movies.theaters.all.inspect %>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/theaters/_form.html.erb
<%= form_for(@theater) do |f| %>
  <% if @theater.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@theater.errors.count, "error") %> prohibited this theater from being saved:</h2>

      <ul>
      <% @theater.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/theaters/edit.html.erb
<h1>Editing theater</h1>

<%= render 'form' %>

<%= link_to 'Show', @theater %> |
<%= link_to 'Back', theaters_path %>

app/views/theaters/index.html.erb
<h1>Listing theaters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Type</th>
    <th>Email</th>
    <th>Number</th>
    <th>Bills Total</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @theaters.each do |theater| %>
  <tr>
    <td><%= theater.name %></td>
    <td><%= theater.location %></td>
    <td><%= theater.type %></td>
    <td><%= theater.email %></td>
    <td><%= theater.number %></td>
    <td title=<%= give_details theater.bills %> ><%= theater.bills.map{|bill| bill.amount}.sum %></td>
    <td><%= link_to "add bill", new_bill_path(:theater_id => theater.id )%></td>
  </tr>
<% end %>
</table>

<br/>

<%= link_to 'New Theater', new_theater_path %>

app/views/theaters/new.html.erb
<h1>New theater</h1>

<%= render 'form' %>

<%= link_to 'Back', theaters_path %>

app/views/theaters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @theater.name %>
</p>

<p>
  <b>Location:</b>
  <%= @theater.location %>
</p>

<p>
  <b>Type:</b>
  <%= @theater.type %>
</p>

<p>
  <b>Email:</b>
  <%= @theater.email %>
</p>


<%= link_to 'Edit', edit_theater_path(@theater) %> |
<%= link_to 'Back', theaters_path %>